name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        build_type: [Debug]
        c_compiler: [clang]
        cpp_compiler: [clang++]
#        include:
#          - os: windows-latest
#            defines: '-DWINDOWS=TRUE'
#        exclude:
#          - os: windows-latest
#            cpp_compiler: g++

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.11.1

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.c_compiler }}
          cxx: ${{ matrix.cpp_compiler }}
          configure-options: -G Ninja ${{ matrix.defines }}
          build-type: ${{ matrix.build_type }}

      - name: All System info
        run: |
          mount

      - name: Test
        working-directory: ${{ runner.workspace }}/build/test
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure -R test_delete_large_item