name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [clang]
        include:
          - os: windows-latest
            c_compiler: clang
            cpp_compiler: clang
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.10.0

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.config.c_compiler }}
          cxx: ${{ matrix.config.cpp_compiler }}
          configure-options: -G Ninja
          build-type: ${{ matrix.config.build_type }}

      - name: Test
        working-directory: ${{ runner.workspace }}/build/test
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure